Update rechunker, take Bazzite's kernel version

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -101,49 +101,18 @@ jobs:
         run: |
           set -xeu pipefail
 
-          FEDORA_MAJOR_VERSION="${{ env.MAJOR_VERSION }}"
-          KERNEL_FLAVOR="${{ env.KERNEL_FLAVOR }}"
-          REPOS=("${{ env.KERNEL_FLAVOR }}-kernel" "akmods" "akmods-extra" "akmods-nvidia")
+          kernel_version=$(curl -fsSL \
+            https://raw.githubusercontent.com/ublue-os/bazzite/refs/heads/main/.github/workflows/build.yml | \
+            grep -m1 'kernel_version:' | \
+            awk '{gsub(/#.*/,""); print $2}' | \
+            xargs)
 
-          declare -A repo_tags
-
-          get_tags() {
-          repo=$1
-          if [[ "$repo" == "${{ env.KERNEL_FLAVOR }}-kernel" ]]; then
-              # bazzite-kernel uses the format without the initial flavor in the tag
-              skopeo list-tags docker://ghcr.io/ublue-os/${repo} | jq -r '.Tags[]' \
-              | grep "^${FEDORA_MAJOR_VERSION}-[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\..*\.fc${FEDORA_MAJOR_VERSION}\.x86_64"
-          else
-              # Other repos use the format with the flavor in the tag
-              skopeo list-tags docker://ghcr.io/ublue-os/${repo} | jq -r '.Tags[]' \
-              | grep "^${KERNEL_FLAVOR}-${FEDORA_MAJOR_VERSION}-[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\..*\.fc${FEDORA_MAJOR_VERSION}\.x86_64"
-          fi
-          }
-
-          for repo in "${REPOS[@]}"; do
-            tags=$(get_tags "$repo")
-            repo_tags[$repo]="$tags"
-          done
-
-          extract_full_version() {
-            echo "$1" | cut -d'-' -f2,3
-          }
-
-          common_versions=($(echo "${repo_tags[${{ env.KERNEL_FLAVOR }}-kernel]}" | while read -r tag; do
-            full_version=$(extract_full_version "$tag")
-
-            if grep -q "$full_version" <<< "${repo_tags[akmods]}" && \
-                grep -q "$full_version" <<< "${repo_tags[akmods-extra]}" && \
-                grep -q "$full_version" <<< "${repo_tags[akmods-nvidia]}"; then
-                echo "$full_version"
-            fi
-          done | sort -V))
-
-          if [ -n "${common_versions[-1]}" ]; then
-            echo "KERNEL=${common_versions[-1]}" >> $GITHUB_OUTPUT
-          else
+          if [ -z "$kernel_version" ]; then
+            echo "Couldn't get Bazzite's pinned kernel version" >&2
             exit 1
           fi
+
+          echo "KERNEL=$kernel_version" >> $GITHUB_OUTPUT
 
       - name: Pull main, akmods, rechunk images
         uses: Wandalen/wretry.action@v3.8.0
@@ -158,7 +127,7 @@ jobs:
             sudo podman pull docker://ghcr.io/ublue-os/akmods-extra:${{ env.KERNEL_FLAVOR }}-${{ env.MAJOR_VERSION }}-${{ steps.kernel.outputs.KERNEL }}
 
             # Add rechunk as well to remove this source of failure
-            sudo podman pull ghcr.io/hhd-dev/rechunk:v0.8.3
+            sudo podman pull ghcr.io/hhd-dev/rechunk:v1.1.3
 
       - name: Wait for COPR builds to complete
       # cursed
@@ -279,9 +248,9 @@ jobs:
       # Reprocess raw-img using rechunker which will delete it
       - name: Run Rechunker
         id: rechunk
-        uses: hhd-dev/rechunk@v1.1.2
+        uses: hhd-dev/rechunk@v1.1.3
         with:
-          rechunk: 'ghcr.io/hhd-dev/rechunk:v0.8.3'
+          rechunk: 'ghcr.io/hhd-dev/rechunk:v1.1.3'
           ref: 'raw-img'
           prev-ref: '${{ steps.generate-prev-ref.outputs.ref }}'
           version: ${{ env.TIMESTAMP_TAG }}
diff --git a/build-image b/build-image
--- a/build-image
+++ b/build-image
@@ -2,47 +2,19 @@
 
 TARGET="$1"
 FEDORA_MAJOR_VERSION="$2"
-KERNEL_FLAVOR="bazzite"
-REPOS=("bazzite-kernel" "akmods" "akmods-extra" "akmods-nvidia")
 
 set -xeu pipefail
 
-declare -A repo_tags
+kernel_version=$(curl -fsSL \
+  https://raw.githubusercontent.com/ublue-os/bazzite/refs/heads/main/.github/workflows/build.yml | \
+  grep -m1 'kernel_version:' | \
+  awk '{gsub(/#.*/,""); print $2}' | \
+  xargs)
 
-get_tags() {
-repo=$1
-if [[ "$repo" == "bazzite-kernel" ]]; then
-    # bazzite-kernel uses the format without the initial flavor in the tag
-    skopeo list-tags docker://ghcr.io/ublue-os/${repo} | jq -r '.Tags[]' \
-    | grep "^${FEDORA_MAJOR_VERSION}-[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\..*\.fc${FEDORA_MAJOR_VERSION}\.x86_64"
-else
-    # Other repos use the format with the flavor in the tag
-    skopeo list-tags docker://ghcr.io/ublue-os/${repo} | jq -r '.Tags[]' \
-    | grep "^${KERNEL_FLAVOR}-${FEDORA_MAJOR_VERSION}-[0-9]\+\.[0-9]\+\.[0-9]\+-[0-9]\+\..*\.fc${FEDORA_MAJOR_VERSION}\.x86_64"
-fi
-}
-
-for repo in "${REPOS[@]}"; do
-  tags=$(get_tags "$repo")
-  repo_tags[$repo]="$tags"
-done
-
-extract_full_version() {
-  echo "$1" | cut -d'-' -f2,3
-}
-
-common_versions=($(echo "${repo_tags[bazzite-kernel]}" | while read -r tag; do
-  full_version=$(extract_full_version "$tag")
-
-  if grep -q "$full_version" <<< "${repo_tags[akmods]}" && \
-      grep -q "$full_version" <<< "${repo_tags[akmods-extra]}" && \
-      grep -q "$full_version" <<< "${repo_tags[akmods-nvidia]}"; then
-      echo "$full_version"
-  fi
-done | sort -V))
-
-if [ -n "${common_versions[-1]}" ]; then
-  podman build . --target "$TARGET" --build-arg KERNEL_VERSION="${common_versions[-1]}" --cap-add SYS_ADMIN
-else
+if [ -z "$kernel_version" ]; then
+  echo "Couldn't get Bazzite's pinned kernel version" >&2
   exit 1
 fi
+
+podman build . --target "$TARGET" --build-arg KERNEL_VERSION="$kernel_version"
+
